### ISSUE TITLE
Accept the options payload from a file for the lifx command

### ISSUE THREAD

**Issue by Djelibeybi** [delfick/photons-core#12]
It would be super peachy keen if the `lifx` command could accept the JSON extras payload as a file so one doesn't need to provide the JSON on the command line.

Example: `lifx lan:transform file:/path/to/myserials.txt -- file:/path/to/transform.json`

**Comment by delfick** [comment]
that shouldn't be too hard. If it was valid json it'd have to be in quotes, so I can treat it differently if it starts with file://

**Comment by delfick** [comment]
done :)
