### ISSUE TITLE
Device finder is not matching on group names with spaces

### ISSUE THREAD

**Issue by Djelibeybi** [delfick/photons-core#15]
If I try to match on a group name which is a single word, it works fine, e.g. `lifx lan:device_finder_info -- '{"group_name": "Kitchen"}'`

However, trying to match with a space (even encoded), does not: `lifx lan:device_finder_info -- '{"group_name": "Dining%20Room"}'`

**Comment by Djelibeybi** [comment]
This impacts Photons Interactor's `matcher` too.  Matching on `group_id` still works and it returns the right string for the group label.

**Comment by delfick** [comment]
the url encoding isn't needed when you specify the matcher with json
